---
- hosts: windows
  tasks:
    - name: Install Chocolatey packages
      win_chocolatey:
        name: "{{ chocolatey_packages }}"
        state: present
      when: chocolatey_packages is defined
    - name: Upgrade Chocolatey packages
      win_chocolatey:
        name: all
        state: latest
    - name: Install packages
      win_package:
        path: "{{ item.path }}"
        product_id: "{{ item.product_id }}"
        state: present
      with_items: "{{ packages }}"
      when: packages is defined