---
- hosts: windows
  tasks:
    - name: Install packages
      win_chocolatey:
        name:
          - 7zip
          - bitwarden
          - chocolateygui
          - discord
          - docker-desktop
          - dotnetcore-sdk
          - dropbox
          - duplicati # not trusted
          - etcher
          - ffmpeg
          - firefox
          - git
          - google-backup-and-sync
          - googlechrome
          - hashtab # not trusted
          - imgburn # not trusted
          - kdiff3
          - libreoffice-fresh
          - microsoft-teams
          - microsoft-windows-terminal
          - mullvad-app # not trusted
          - nodejs
          - paint.net
          - plex
          - samsung-magician # not trusted
          - spotify
          - steam
          - syncthing
          - teamviewer
          - treesizefree
          - veracrypt
          - visualstudio2019community
          - visualstudio2019community-preview # exempt from moderation, failed because of missing preview flag?
          - vlc
          - vscode
           #- anydvd 
           #- geforce-experience 
           #- geforce-game-ready-driver 
           #- handbrake 
           #- jellyfin 
           #- lossless-cut 
           #- makemkv 
           #- malwarebytes 
           #- nvidia-display-driver 
           #- pycharm-edu 
           #- sqlitebrowser  # not trusted
        state: present
    - name: Upgrade packages
      win_chocolatey:
        name: all
        state: latest